#!/usr/bin/python3.6
from matrix import *
from transformation import *
from parse import *
from print_matrix import *
from print_res import *
from math import *

try:
    change_h_to_H()
    args = parse_all()
    print_infos(args)
    xpos = coord_to_matrix(args.x, args.y)
    xres = get_xres(args)
    print_matrix(xres)
    xpos = matrix_product(xres, xpos)
    print_res(args.x, args.y, xpos)
except:
    print("Need at least x y args and one transformation")
    exit(84)
